/**
 * GXVIS Metrics Collection
 * Implements application-level metrics using Prometheus client
 * Aligns with GXVIS Article 13 (派生データの保存義務) and Article 27 (監査ログ義務)
 */

import client from 'prom-client';

// Create Registry
export const register = new client.Registry();

// Add default metrics (CPU, memory, GC, event loop)
client.collectDefaultMetrics({
  register,
  prefix: 'gxvis_nodejs_',
  gcDurationBuckets: [0.001, 0.01, 0.1, 1, 2, 5],
});

//═════════════════════════════════════════════════════════════════
// HTTP Metrics (RED Method: Rate, Errors, Duration)
//═════════════════════════════════════════════════════════════════

// Counter: Total HTTP requests
export const httpRequestsTotal = new client.Counter({
  name: 'gxvis_http_requests_total',
  help: 'Total number of HTTP requests',
  labelNames: ['method', 'route', 'status'],
  registers: [register],
});

// Histogram: HTTP request duration (for P50/P95/P99)
export const httpRequestDuration = new client.Histogram({
  name: 'gxvis_http_request_duration_seconds',
  help: 'Duration of HTTP requests in seconds',
  labelNames: ['method', 'route', 'status'],
  buckets: [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 2, 5, 10, 30, 60], // 1ms to 60s
  registers: [register],
});

// Gauge: Active HTTP connections
export const activeConnections = new client.Gauge({
  name: 'gxvis_http_active_connections',
  help: 'Number of active HTTP connections',
  registers: [register],
});

//═════════════════════════════════════════════════════════════════
// RSS Feed Fetching Metrics
//═════════════════════════════════════════════════════════════════

// Counter: RSS fetch operations
export const rssFetchTotal = new client.Counter({
  name: 'gxvis_rss_fetch_total',
  help: 'Total number of RSS fetch operations',
  labelNames: ['feed_name', 'status'], // status: success, error
  registers: [register],
});

// Histogram: RSS fetch duration
export const rssFetchDuration = new client.Histogram({
  name: 'gxvis_rss_fetch_duration_seconds',
  help: 'Duration of RSS fetch operations in seconds',
  labelNames: ['feed_name'],
  buckets: [0.1, 0.5, 1, 2, 5, 10, 30, 60, 120], // 100ms to 2min
  registers: [register],
});

// Counter: RSS items fetched
export const rssItemsFetched = new client.Counter({
  name: 'gxvis_rss_items_fetched_total',
  help: 'Total number of RSS items fetched',
  labelNames: ['feed_name', 'is_new'], // is_new: true, false
  registers: [register],
});

//═════════════════════════════════════════════════════════════════
// Draft Generation Metrics (Core Business Logic)
//═════════════════════════════════════════════════════════════════

// Counter: Draft generation operations
export const draftGenerationTotal = new client.Counter({
  name: 'gxvis_draft_generation_total',
  help: 'Total number of draft generation operations',
  labelNames: ['status', 'template_type'], // status: success, error
  registers: [register],
});

// Histogram: Draft generation duration (AI processing time)
export const draftGenerationDuration = new client.Histogram({
  name: 'gxvis_draft_generation_duration_seconds',
  help: 'Duration of draft generation operations in seconds',
  labelNames: ['template_type'],
  buckets: [0.5, 1, 2, 5, 10, 15, 30, 60, 120], // 500ms to 2min
  registers: [register],
});

// Gauge: Draft generation queue length
export const draftGenerationQueueLength = new client.Gauge({
  name: 'gxvis_draft_generation_queue_length',
  help: 'Number of items waiting for draft generation',
  registers: [register],
});

// Counter: Drafts generated by template
export const draftsGeneratedByTemplate = new client.Counter({
  name: 'gxvis_drafts_generated_by_template_total',
  help: 'Total number of drafts generated by template type',
  labelNames: ['template_code'],
  registers: [register],
});

//═════════════════════════════════════════════════════════════════
// Human Decision Metrics (Article 14: 人間の責務)
//═════════════════════════════════════════════════════════════════

// Counter: Review decisions
export const reviewDecisionsTotal = new client.Counter({
  name: 'gxvis_review_decisions_total',
  help: 'Total number of review decisions made by humans',
  labelNames: ['action'], // action: approve, reject, posted
  registers: [register],
});

// Histogram: Time from draft creation to decision
export const draftReviewDuration = new client.Histogram({
  name: 'gxvis_draft_review_duration_seconds',
  help: 'Time from draft creation to human decision in seconds',
  labelNames: ['action'],
  buckets: [60, 300, 900, 1800, 3600, 7200, 14400, 43200, 86400], // 1min to 1day
  registers: [register],
});

// Counter: Draft edits (text modifications)
export const draftEditsTotal = new client.Counter({
  name: 'gxvis_draft_edits_total',
  help: 'Total number of draft text edits by humans',
  labelNames: ['has_note'], // has_note: true, false
  registers: [register],
});

//═════════════════════════════════════════════════════════════════
// Database Metrics
//═════════════════════════════════════════════════════════════════

// Counter: Database queries
export const dbQueriesTotal = new client.Counter({
  name: 'gxvis_db_queries_total',
  help: 'Total number of database queries',
  labelNames: ['operation', 'model', 'status'], // operation: findMany, create, update, delete
  registers: [register],
});

// Histogram: Database query duration
export const dbQueryDuration = new client.Histogram({
  name: 'gxvis_db_query_duration_seconds',
  help: 'Duration of database queries in seconds',
  labelNames: ['operation', 'model'],
  buckets: [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 2, 5], // 1ms to 5s
  registers: [register],
});

// Gauge: Database connection pool
export const dbConnectionPoolSize = new client.Gauge({
  name: 'gxvis_db_connection_pool_size',
  help: 'Number of active database connections',
  labelNames: ['state'], // state: active, idle, waiting
  registers: [register],
});

//═════════════════════════════════════════════════════════════════
// Background Job Metrics (Cloud Scheduler)
//═════════════════════════════════════════════════════════════════

// Counter: Background job executions
export const jobExecutionsTotal = new client.Counter({
  name: 'gxvis_job_executions_total',
  help: 'Total number of background job executions',
  labelNames: ['job_type', 'status'], // job_type: fetch_rss, generate_drafts, status: success, failed
  registers: [register],
});

// Histogram: Background job duration
export const jobExecutionDuration = new client.Histogram({
  name: 'gxvis_job_execution_duration_seconds',
  help: 'Duration of background job executions in seconds',
  labelNames: ['job_type'],
  buckets: [1, 5, 10, 30, 60, 120, 300, 600, 1800], // 1s to 30min
  registers: [register],
});

// Gauge: Job run status (current running jobs)
export const activeJobs = new client.Gauge({
  name: 'gxvis_active_jobs',
  help: 'Number of currently running background jobs',
  labelNames: ['job_type'],
  registers: [register],
});

//═════════════════════════════════════════════════════════════════
// Business Metrics (KPIs)
//═════════════════════════════════════════════════════════════════

// Gauge: Total drafts by status
export const draftsByStatus = new client.Gauge({
  name: 'gxvis_drafts_by_status',
  help: 'Total number of drafts by status',
  labelNames: ['status'], // pending, approved, rejected, posted
  registers: [register],
});

// Gauge: Total ingested items in last 24h
export const ingestedItemsLast24h = new client.Gauge({
  name: 'gxvis_ingested_items_last_24h',
  help: 'Total number of items ingested in the last 24 hours',
  labelNames: ['source_type'], // X_SEARCH, RSS, YOUTUBE_SEARCH, YOUTUBE_CHANNEL, MANUAL
  registers: [register],
});

// Counter: Buzz candidates identified
export const buzzCandidatesTotal = new client.Counter({
  name: 'gxvis_buzz_candidates_total',
  help: 'Total number of buzz candidates identified',
  labelNames: ['score_range'], // 0-30, 30-50, 50-70, 70-100
  registers: [register],
});

//═════════════════════════════════════════════════════════════════
// Error Tracking
//═════════════════════════════════════════════════════════════════

// Counter: Application errors
export const applicationErrorsTotal = new client.Counter({
  name: 'gxvis_application_errors_total',
  help: 'Total number of application errors',
  labelNames: ['error_type', 'component'], // component: rss_fetcher, draft_generator, api
  registers: [register],
});

// Counter: API validation errors
export const validationErrorsTotal = new client.Counter({
  name: 'gxvis_validation_errors_total',
  help: 'Total number of validation errors',
  labelNames: ['endpoint', 'error_field'],
  registers: [register],
});

//═════════════════════════════════════════════════════════════════
// Helper Functions
//═════════════════════════════════════════════════════════════════

/**
 * Track HTTP request metrics
 */
export function trackHttpRequest(
  method: string,
  route: string,
  statusCode: number,
  durationMs: number
) {
  const status = statusCode.toString();

  httpRequestsTotal.inc({ method, route, status });
  httpRequestDuration.observe({ method, route, status }, durationMs / 1000);
}

/**
 * Track RSS fetch operation
 */
export function trackRssFetch(
  feedName: string,
  status: 'success' | 'error',
  durationMs: number,
  itemsFetched: number,
  newItems: number
) {
  rssFetchTotal.inc({ feed_name: feedName, status });
  rssFetchDuration.observe({ feed_name: feedName }, durationMs / 1000);

  if (itemsFetched > 0) {
    rssItemsFetched.inc({ feed_name: feedName, is_new: 'false' }, itemsFetched - newItems);
    rssItemsFetched.inc({ feed_name: feedName, is_new: 'true' }, newItems);
  }
}

/**
 * Track draft generation operation
 */
export function trackDraftGeneration(
  templateType: string,
  status: 'success' | 'error',
  durationMs: number
) {
  draftGenerationTotal.inc({ status, template_type: templateType });
  draftGenerationDuration.observe({ template_type: templateType }, durationMs / 1000);
}

/**
 * Track database query
 */
export function trackDbQuery(
  operation: string,
  model: string,
  status: 'success' | 'error',
  durationMs: number
) {
  dbQueriesTotal.inc({ operation, model, status });
  dbQueryDuration.observe({ operation, model }, durationMs / 1000);
}

/**
 * Track background job execution
 */
export function trackJobExecution(
  jobType: string,
  status: 'success' | 'failed',
  durationMs: number
) {
  jobExecutionsTotal.inc({ job_type: jobType, status });
  jobExecutionDuration.observe({ job_type: jobType }, durationMs / 1000);
}

/**
 * Track review decision
 */
export function trackReviewDecision(
  action: 'approve' | 'reject' | 'posted',
  draftAgeSeconds: number,
  hasEdit: boolean,
  hasNote: boolean
) {
  reviewDecisionsTotal.inc({ action });
  draftReviewDuration.observe({ action }, draftAgeSeconds);

  if (hasEdit) {
    draftEditsTotal.inc({ has_note: hasNote.toString() });
  }
}

/**
 * Update business metrics (called periodically)
 */
export async function updateBusinessMetrics(prisma: any) {
  try {
    // Drafts by status
    const draftStatusCounts = await prisma.draftPost.groupBy({
      by: ['status'],
      _count: { _all: true },
    });

    for (const { status, _count } of draftStatusCounts) {
      draftsByStatus.set({ status }, _count._all);
    }

    // Ingested items in last 24h
    const twentyFourHoursAgo = new Date(Date.now() - 24 * 60 * 60 * 1000);
    const ingestedCounts = await prisma.ingestItem.groupBy({
      by: ['source'],
      where: {
        ingestedAt: { gte: twentyFourHoursAgo },
      },
      _count: { _all: true },
    });

    for (const { source, _count } of ingestedCounts) {
      const sourceInfo = await prisma.source.findUnique({ where: { id: source } });
      if (sourceInfo) {
        ingestedItemsLast24h.set({ source_type: sourceInfo.type }, _count._all);
      }
    }
  } catch (error) {
    console.error('Failed to update business metrics:', error);
  }
}

/**
 * Get score range label for buzz candidates
 */
export function getScoreRange(score: number): string {
  if (score < 30) return '0-30';
  if (score < 50) return '30-50';
  if (score < 70) return '50-70';
  return '70-100';
}
