# Ω Statistics Template for AIT42 Agents
# Version: 1.0.0
# This template defines the structure for Omega-based performance metrics

agent_name: "agent-name-here"

# ========== Standard Statistics (Existing) ==========
total_tasks: 0
successful_tasks: 0
failed_tasks: 0
success_rate: 0.0

average_quality_score: 0.0
average_duration_ms: 0

# ========== Ω Statistics (New) ==========
omega_metrics:

  # 1. Big-Omega (Ω): Performance Lower Bounds
  #    Guarantees minimum performance levels
  performance_bounds:
    min_quality_score: 75          # Minimum quality score ever achieved
    min_success_rate: 0.80          # Minimum success rate threshold
    max_latency_ms: 5000            # Maximum acceptable latency

    # Historical worst case (for reference)
    worst_case:
      quality_score: 0              # Lowest quality score encountered
      success_rate: 0.0             # Lowest success rate period
      latency_ms: 0                 # Highest latency encountered

  # 2. Prime Omega (素因数Ω): Dependency Analysis
  #    Measures coupling and complexity
  dependencies:
    omega: 0                        # Total dependencies (with duplicates)
    little_omega: 0                 # Unique dependencies
    coupling_ratio: 1.0             # Ω/ω (ideal: 1.0, warning: >2.0)

    # Detailed dependency list
    dependencies_list:
      tools: []                     # e.g., [Read, Write, Edit, Bash]
      agents: []                    # e.g., [api-designer, database-designer]
      external: []                  # e.g., [npm, git, docker]

    # Coupling health indicators
    coupling_health:
      status: "good"                # good (<1.5), fair (1.5-2.0), poor (>2.0)
      recommendation: ""            # Empty if good, else refactoring suggestions

  # 3. Chaitin's Omega (Ω): Completion Probability
  #    Predicts task success probability
  completion_probability:
    base_omega: 0.0                 # Overall success rate

    # Success rate by task complexity (1-10 scale)
    by_complexity:
      low: 0.0        # Complexity 1-3: Simple tasks
      medium: 0.0     # Complexity 4-6: Moderate tasks
      high: 0.0       # Complexity 7-10: Complex tasks

    # Success rate by task category
    by_category:
      implementation: 0.0
      refactoring: 0.0
      testing: 0.0
      documentation: 0.0
      debugging: 0.0

    # Confidence intervals
    confidence_interval: 0.05       # ±5% uncertainty
    sample_size: 0                  # Number of tasks used for calculation

    # Prediction accuracy tracking
    prediction_accuracy:
      total_predictions: 0
      accurate_predictions: 0       # Within confidence interval
      accuracy_rate: 0.0            # accurate/total

# ========== Learning Metrics ==========
learning_metrics:
  # Bayesian update parameters
  learning_rate: 0.1                # Alpha for exponential moving average

  # Performance trends
  quality_trend:
    direction: "stable"             # improving, stable, declining
    rate: 0.0                       # Change rate per task

  success_trend:
    direction: "stable"
    rate: 0.0

  # Specialization score (0-1)
  specialization:
    primary_category: ""            # Most successful category
    specialization_score: 0.0       # How specialized vs generalist
    categories:
      implementation: 0
      refactoring: 0
      testing: 0
      documentation: 0
      debugging: 0

# ========== Recent Tasks (with Ω predictions) ==========
recent_tasks:
  # Example entry:
  # - task_id: "2025-11-06-001"
  #   task_description: "Implement user authentication API"
  #   complexity: 5
  #   category: "implementation"
  #
  #   omega_predicted:
  #     completion_probability: 0.85
  #     estimated_quality: 80
  #     estimated_duration_ms: 180000
  #
  #   omega_actual:
  #     completion_probability: 1.0  # 1.0 if success, 0.0 if fail
  #     actual_quality: 88
  #     actual_duration_ms: 165000
  #
  #   prediction_error:
  #     quality_error: 8            # actual - predicted
  #     duration_error_ms: -15000   # actual - predicted
  #     success_predicted_correctly: true

# ========== Metadata ==========
metadata:
  last_updated: ""                  # ISO 8601 timestamp
  schema_version: "1.0.0"
  omega_integration_date: ""        # When Ω stats were first added

  # Quality gates
  passes_quality_gates:
    min_quality: false              # quality >= 75
    min_success_rate: false         # success_rate >= 0.80
    acceptable_coupling: false      # coupling_ratio < 2.0

  overall_health: "unknown"         # excellent, good, fair, poor, unknown
