agent_name: doc-reviewer
total_tasks: 0
successful_tasks: 0
failed_tasks: 0
success_rate: 0
avg_quality_score: 0
avg_duration_ms: 0
last_updated: 2025-11-04T00:00:00Z
recent_tasks: []
trends:
  success_rate_trend: 0
  quality_score_trend: 0
  avg_duration_trend: 0
specializations: {}
omega_metrics:
  performance_bounds:
    min_quality_score: 81
    min_success_rate: 0.8
    max_latency_ms: 5000
    worst_case:
      quality_score: 81
      success_rate: 0
      latency_ms: 0
  dependencies:
    omega: 34
    little_omega: 21
    coupling_ratio: 1.619047619047619
    dependencies_list:
      tools:
        - Read
        - Write
        - Edit
        - Grep
        - Glob
        - Bash
      agents:
        - doc-reviewer
        - 0-100
        - doc-files
        - doc-templates
        - validate-openapi
        - validate-code-comments
        - 75-89
        - 60-74
        - 2025-11-06
        - api-validation-results
        - doc-coverage-report
        - documentation-quality-report
        - generate-readme
        - generate-doc-quality
        - Up-to-date
      external: []
    coupling_health:
      status: fair
      recommendation: Moderate coupling. Monitor and consider refactoring if increasing.
  completion_probability:
    base_omega: 0
    by_complexity:
      low: 0.9600000000000001
      medium: 0.8600000000000001
      high: 0.66
    by_category:
      implementation: 0
      refactoring: 0
      testing: 0
      documentation: 0
      debugging: 0
    confidence_interval: 0.05
    sample_size: 0
    prediction_accuracy:
      total_predictions: 0
      accurate_predictions: 0
      accuracy_rate: 0
learning_metrics:
  learning_rate: 0.1
  quality_trend:
    direction: stable
    rate: 0
  success_trend:
    direction: stable
    rate: 0
  specialization:
    primary_category: implementation
    specialization_score: 0
    categories:
      implementation: 0
      refactoring: 0
      testing: 0
      documentation: 0
      debugging: 0
metadata:
  last_updated: 2025-11-06T09:25:44.406Z
  schema_version: 1.0.0
  omega_integration_date: 2025-11-06
  passes_quality_gates:
    min_quality: true
    min_success_rate: true
    acceptable_coupling: true
  overall_health: excellent
