agent_name: feedback-analyzer
total_tasks: 0
successful_tasks: 0
failed_tasks: 0
success_rate: 0
avg_quality_score: 0
avg_duration_ms: 0
last_updated: 2025-11-04T00:00:00Z
recent_tasks: []
trends:
  success_rate_trend: 0
  quality_score_trend: 0
  avg_duration_trend: 0
specializations: {}
omega_metrics:
  performance_bounds:
    min_quality_score: 88
    min_success_rate: 0.8
    max_latency_ms: 5000
    worst_case:
      quality_score: 88
      success_rate: 0
      latency_ms: 0
  dependencies:
    omega: 13
    little_omega: 12
    coupling_ratio: 1.0833333333333333
    dependencies_list:
      tools:
        - Read
        - Write
        - Edit
        - Grep
        - Glob
        - Bash
      agents:
        - feedback-analyzer
        - support-ticket
        - 0-10
        - keyword-based
        - Real-time
        - Follow-up
      external: []
    coupling_health:
      status: good
      recommendation: ""
  completion_probability:
    base_omega: 0
    by_complexity:
      low: 0.99
      medium: 0.93
      high: 0.73
    by_category:
      implementation: 0
      refactoring: 0
      testing: 0
      documentation: 0
      debugging: 0
    confidence_interval: 0.05
    sample_size: 0
    prediction_accuracy:
      total_predictions: 0
      accurate_predictions: 0
      accuracy_rate: 0
learning_metrics:
  learning_rate: 0.1
  quality_trend:
    direction: stable
    rate: 0
  success_trend:
    direction: stable
    rate: 0
  specialization:
    primary_category: implementation
    specialization_score: 0
    categories:
      implementation: 0
      refactoring: 0
      testing: 0
      documentation: 0
      debugging: 0
metadata:
  last_updated: 2025-11-06T09:25:44.409Z
  schema_version: 1.0.0
  omega_integration_date: 2025-11-06
  passes_quality_gates:
    min_quality: true
    min_success_rate: true
    acceptable_coupling: true
  overall_health: excellent
