agent_name: mutation-tester
total_tasks: 0
successful_tasks: 0
failed_tasks: 0
success_rate: 0
avg_quality_score: 0
avg_duration_ms: 0
last_updated: 2025-11-04T00:00:00Z
recent_tasks: []
trends:
  success_rate_trend: 0
  quality_score_trend: 0
  avg_duration_trend: 0
specializations: {}
omega_metrics:
  performance_bounds:
    min_quality_score: 74
    min_success_rate: 0.8
    max_latency_ms: 5000
    worst_case:
      quality_score: 74
      success_rate: 0
      latency_ms: 0
  dependencies:
    omega: 38
    little_omega: 34
    coupling_ratio: 1.1176470588235294
    dependencies_list:
      tools:
        - Read
        - Write
        - Edit
        - Grep
        - Glob
        - Bash
      agents:
        - mutation-tester
        - mutation-operators
        - mutation-score
        - surviving-mutants
        - killed-mutants
        - mutation-report
        - equivalent-mutants
        - run-mutation-testing
        - analyze-survivors
        - generate-recommendations
        - stryker-mutator
        - clear-text
        - typescript-checker
        - low-value
        - stryker-tmp
        - custom-mutators
        - generate-mutation-report
        - font-family
        - sans-serif
        - font-size
        - font-weight
        - border-collapse
        - text-align
        - background-color
        - re-runs
        - high-value
        - Auto-detect
        - Auto-detected
      external: []
    coupling_health:
      status: good
      recommendation: ""
  completion_probability:
    base_omega: 0
    by_complexity:
      low: 0.89
      medium: 0.79
      high: 0.59
    by_category:
      implementation: 0
      refactoring: 0
      testing: 0
      documentation: 0
      debugging: 0
    confidence_interval: 0.05
    sample_size: 0
    prediction_accuracy:
      total_predictions: 0
      accurate_predictions: 0
      accuracy_rate: 0
learning_metrics:
  learning_rate: 0.1
  quality_trend:
    direction: stable
    rate: 0
  success_trend:
    direction: stable
    rate: 0
  specialization:
    primary_category: implementation
    specialization_score: 0
    categories:
      implementation: 0
      refactoring: 0
      testing: 0
      documentation: 0
      debugging: 0
metadata:
  last_updated: 2025-11-06T09:25:44.424Z
  schema_version: 1.0.0
  omega_integration_date: 2025-11-06
  passes_quality_gates:
    min_quality: false
    min_success_rate: true
    acceptable_coupling: true
  overall_health: good
