agent_name: release-manager
total_tasks: 0
successful_tasks: 0
failed_tasks: 0
success_rate: 0
avg_quality_score: 0
avg_duration_ms: 0
last_updated: 2025-11-04T00:00:00Z
recent_tasks: []
trends:
  success_rate_trend: 0
  quality_score_trend: 0
  avg_duration_trend: 0
specializations: {}
omega_metrics:
  performance_bounds:
    min_quality_score: 43
    min_success_rate: 0.8
    max_latency_ms: 5000
    worst_case:
      quality_score: 43
      success_rate: 0
      latency_ms: 0
  dependencies:
    omega: 143
    little_omega: 62
    coupling_ratio: 2.306451612903226
    dependencies_list:
      tools:
        - Read
        - Write
        - Edit
        - Grep
        - Glob
        - Bash
      agents:
        - release-manager
        - Multi-stage
        - release-management
        - standard-version
        - release-please-config
        - semantic-release
        - changelog-template
        - github-actions
        - deploy-staging
        - deploy-production
        - create-release
        - deploy-canary
        - release-gates
        - quality-gate
        - approval-workflow
        - dora-metrics
        - release-dashboard
        - config-conventional
        - type-enum
        - subject-case
        - upper-case
        - subject-full-stop
        - header-max-length
        - release-type
        - package-name
        - my-app
        - changelog-sections
        - extra-files
        - package-lock
        - pull-requests
        - release-please
        - runs-on
        - ubuntu-latest
        - release-created
        - tag-name
        - google-github-actions
        - release-please-action
        - changelog-types
        - setup-node
        - node-version
        - coverage-summary
        - severity-threshold
        - backend-api
        - slack-github-action
        - channel-id
        - slack-message
        - pre-deployment-checks
        - Pre-Deployment
        - load-test
        - manual-approval
        - production-approval
        - backend-api-canary
        - deploy-full
        - DD-API-KEY
        - Content-Type
        - One-command
      external: []
    coupling_health:
      status: poor
      recommendation: High coupling detected. Consider refactoring to reduce dependencies.
  completion_probability:
    base_omega: 0
    by_complexity:
      low: 0.58
      medium: 0.48
      high: 0.5
    by_category:
      implementation: 0
      refactoring: 0
      testing: 0
      documentation: 0
      debugging: 0
    confidence_interval: 0.05
    sample_size: 0
    prediction_accuracy:
      total_predictions: 0
      accurate_predictions: 0
      accuracy_rate: 0
learning_metrics:
  learning_rate: 0.1
  quality_trend:
    direction: stable
    rate: 0
  success_trend:
    direction: stable
    rate: 0
  specialization:
    primary_category: implementation
    specialization_score: 0
    categories:
      implementation: 0
      refactoring: 0
      testing: 0
      documentation: 0
      debugging: 0
metadata:
  last_updated: 2025-11-06T09:25:44.428Z
  schema_version: 1.0.0
  omega_integration_date: 2025-11-06
  passes_quality_gates:
    min_quality: false
    min_success_rate: true
    acceptable_coupling: false
  overall_health: fair
