agent_name: security-tester
total_tasks: 0
successful_tasks: 0
failed_tasks: 0
success_rate: 0
avg_quality_score: 0
avg_duration_ms: 0
last_updated: 2025-11-04T00:00:00Z
recent_tasks: []
trends:
  success_rate_trend: 0
  quality_score_trend: 0
  avg_duration_trend: 0
specializations: {}
omega_metrics:
  performance_bounds:
    min_quality_score: 64
    min_success_rate: 0.8
    max_latency_ms: 5000
    worst_case:
      quality_score: 64
      success_rate: 0
      latency_ms: 0
  dependencies:
    omega: 100
    little_omega: 65
    coupling_ratio: 1.5384615384615385
    dependencies_list:
      tools:
        - Read
        - Write
        - Edit
        - Grep
        - Glob
        - Bash
      agents:
        - security-tester
        - Dependency-Check
        - broken-auth
        - api-pentest
        - auth-pentest
        - static-analysis
        - bandit-config
        - semgrep-rules
        - dependency-scan
        - audit-report
        - vulnerability-report
        - cvss-scores
        - zap-scan
        - dependency-check
        - security-audit
        - valid-search
        - wrong-password
        - lockout-test
        - a-f0-9
        - Cross-Site
        - double-escaped
        - Content-Security-Policy
        - content-security-policy
        - script-src
        - DOM-based
        - user-controlled
        - user-content
        - state-changing
        - X-CSRF-Token
        - set-cookie
        - zap2docker-stable
        - zap-cli
        - active-scan
        - zap-report
        - high-risk
        - npm-audit
        - snyk-report
        - hardcoded-secret
        - pattern-either
        - sql-injection-risk
        - command-injection
        - insecure-random
        - missing-csrf-protection
        - semgrep-results
        - bandit-results
        - output-file
        - eslint-security
        - generate-security-report
        - font-family
        - sans-serif
        - font-weight
        - border-collapse
        - text-align
        - background-color
        - border-radius
        - Code-level
        - 0-8
        - Non-Destructive
        - 90-day
      external: []
    coupling_health:
      status: fair
      recommendation: Moderate coupling. Monitor and consider refactoring if increasing.
  completion_probability:
    base_omega: 0
    by_complexity:
      low: 0.79
      medium: 0.6900000000000001
      high: 0.5
    by_category:
      implementation: 0
      refactoring: 0
      testing: 0
      documentation: 0
      debugging: 0
    confidence_interval: 0.05
    sample_size: 0
    prediction_accuracy:
      total_predictions: 0
      accurate_predictions: 0
      accuracy_rate: 0
learning_metrics:
  learning_rate: 0.1
  quality_trend:
    direction: stable
    rate: 0
  success_trend:
    direction: stable
    rate: 0
  specialization:
    primary_category: implementation
    specialization_score: 0
    categories:
      implementation: 0
      refactoring: 0
      testing: 0
      documentation: 0
      debugging: 0
metadata:
  last_updated: 2025-11-06T09:25:44.432Z
  schema_version: 1.0.0
  omega_integration_date: 2025-11-06
  passes_quality_gates:
    min_quality: false
    min_success_rate: true
    acceptable_coupling: true
  overall_health: good
